name: 08-Using variables

on:  
    workflow_dispatch:

env:
    workflow_var: 'This is workflow variable'
    overwritten: 'This variable will be overwritten in job and step level'
    

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: 'This is Job variable'
            overwritten: 'I have been overwritten in job level'
        steps:
            - name: Print Env variables
              env: 
                STEP_VAR: 'This is Step variable'
                step_var2: 'This is step var 2'
              run: |
                echo "Step env var: ${{ env.STEP_VAR }}"
                echo "Step env var 2: $step_var2"
                echo "Job env var: ${{ env.JOB_VAR }}"
                echo "Workflow env var: ${{ env.workflow_var }}"
                echo "Overwritten variable in step level: ${{ env.overwritten }}"
            - name: Overwritten job variable
              env:
                overwritten: 'I have been overwritten in step level'
              run: |
                echo "Overwritten variable in job level: ${{env.overwritten}}"


