name: 13- using caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: 'Use cache or not'
                type: boolean
                default: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cache node modules
              id: cache-node-modules
              uses: actions/cache@v3
              with: