name: 16- working with environments
run-name: 16- working with environments | env - ${{ inputs.target-env }}

on:
    workflow_dispatch:
        inputs:
                target-env:
                    type: environment
                    default: staging

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env:
            my_env_var: ${{ vars.my_env_var || 'default value' }}
        steps:
            - name: echo environment
              run: echo "Env var is ${{ env.my_env_var }}"