name: 19-2-manage concurrency

on:
    workflow_dispatch:


jobs:
    ping-with-concurrency:
        concurrency:
            group: ${{github.workflow}}-${{github.ref}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Ping url
              id: ping-url
              run: |
                    echo "Pinging url..."
                    sleep 50
                    echo "Done pinging url."
    
    ping-without-concurrency:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Ping url
              id: ping-url
              run: |
                    echo "Pinging url..."
                    sleep 50
                    echo "Done pinging url."